# Configuración de API para OpenCage
OPENCAGE_API_KEY=95f749fa90c54594b555b94990e6ea8c



# Mapeo de columnas para importación por defecto
import.default.columna.fecha=1
import.default.columna.hora=2
import.default.columna.ubicacion=3
import.default.columna.tipoMovimiento=4
import.default.columna.userId=6

# OPCIONES DE IDENTIFICACION PARA tipoMovimiento
tipos.entrada=entrada,in,ingreso,login,checkin,acceso,inicio,jornada,iniciar,entro,marco entrada,start shift,begin,clock in
tipos.salida=salida,out,egreso,logout,checkout,finalizo,salio,termino jornada,fin,retirada,end shift,clock out
tipos.pausa_inicio=pausa inicio,break,stop,inicio pausa,comienzo pausa,p.inicio,breakstart,tomar descanso,inicio descanso,inicio break
tipos.pausa_fin=pausa fin,reanudar,continuar,fin pausa,fin de pausa,p.fin,resume,vuelta,return from break,volver descanso,retoma
tipos.ubicacion=ubicacion,gps,posicion,coordenada,geo,latlon,latitud,longitud,localizacion,tracking,ubic,gps check,gps track,geopos
tipos.manual=manual,carga manual,editado,digitado,corregido,ingresado a mano,ajuste,modificado,entrada editada,entrada directa,manualmente


# CONFIGURACIONES GLOBALES POR DEFECTO
# Tolerancia general en minutos para entradas y salidas (aplica si el turno no tiene una definida)
tolerancia.minutos=5
# Diferencia máxima (en minutos) para considerar una fichada como duplicada
duplicado.delta.min=5
# Máximo número de fichadas válidas por jornada (Entrada, Salida, Pausa, etc.)
max.registros.jornada=6
# ¿Cerrar automáticamente la jornada si no hay salida y se alcanza el límite horario?
jornada.autocierre=true
# Hora máxima (formato 0-23) para cierre automático si falta salida
jornada.hora.maxima=23
# ¿Permitir múltiples pausas en un mismo día?
pausa.multiple=false
# ¿Aceptar fichadas fuera del horario del turno (entrada/salida esperada)?
aceptar.fuera.turno=false
# ¿Registrar los movimientos que solo indican ubicación (sin entrada/salida)?
solo.ubicacion=true
# ¿Activar el registro de anomalías e inconsistencias detectadas?
auditoria.anomalias=true

# ============================