/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-07 14:59:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xava.editors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.openxava.model.meta.MetaProperty;
import org.openxava.util.Strings;
import com.sta.biometric.anotaciones.SmallImage;
import java.lang.reflect.Method;
import java.lang.reflect.Field;

public final class SmallImageEditor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Soporte/AppData/Local/Temp/0-biometric/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/xava/imports.jsp", Long.valueOf(1763155074000L));
    _jspx_dependants.put("jar:file:/C:/Users/Soporte/AppData/Local/Temp/0-biometric/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1765119561128L));
    _jspx_dependants.put("/WEB-INF/openxava.tld", Long.valueOf(1763155074000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("org.openxava.model.meta.MetaProperty");
    _jspx_imports_classes.add("com.sta.biometric.anotaciones.SmallImage");
    _jspx_imports_classes.add("org.openxava.util.Strings");
    _jspx_imports_classes.add("java.lang.reflect.Field");
    _jspx_imports_classes.add("java.lang.reflect.Method");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <style>\r\n");
      out.write("                                .small-image-container {\r\n");
      out.write("                                    display: inline-block;\r\n");
      out.write("                                    vertical-align: middle;\r\n");
      out.write("                                    margin-right: 10px;\r\n");
      out.write("                                    border-radius: 5px;\r\n");
      out.write("                                    border: 1px solid #ddd;\r\n");
      out.write("                                    box-sizing: border-box;\r\n");
      out.write("                                    background-color: #f0f0f0;\r\n");
      out.write("                                }\r\n");
      out.write("\r\n");
      out.write("                                .small-image-shadow {\r\n");
      out.write("                                    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.4);\r\n");
      out.write("                                    transform: perspective(500px) rotateY(10deg);\r\n");
      out.write("                                    transition: transform 0.3s ease;\r\n");
      out.write("                                }\r\n");
      out.write("\r\n");
      out.write("                                .small-image-shadow:hover {\r\n");
      out.write("                                    transform: perspective(500px) rotateY(0deg) scale(1.1);\r\n");
      out.write("                                    z-index: 10;\r\n");
      out.write("                                }\r\n");
      out.write("                            </style>\r\n");
      out.write("\r\n");
      out.write("                            ");
 String propertyKey=request.getParameter("propertyKey"); MetaProperty p=(MetaProperty)
                                request.getAttribute(propertyKey); Object value=request.getAttribute(propertyKey
                                + ".value" ); String foid=(value !=null) ? value.toString() : "" ; String
                                applicationName=request.getParameter("application"); String
                                module=request.getParameter("module"); /* Default values */ int size=50; boolean
                                shadow=false; String extraStyle="" ; boolean annotationFound=false; /* Attempt to read
                                annotation via reflection */ if (p !=null) { try { Class<?> beanClass =
                                p.getMetaModel().getPOJOClass();
                                String propertyName = p.getName();

                                /* Try getter method first */
                                String getterName = "get" + Strings.firstUpper(propertyName);
                                Method m = null;
                                try {
                                m = beanClass.getMethod(getterName);
                                } catch (NoSuchMethodException ie) {
                                /* try isBoolean */
                                try {
                                m = beanClass.getMethod("is" + Strings.firstUpper(propertyName));
                                } catch (NoSuchMethodException ie2) {
                                /* ignore */
                                }
                                }

                                if (m != null && m.isAnnotationPresent(SmallImage.class)) {
                                SmallImage ann = m.getAnnotation(SmallImage.class);
                                size = ann.size();
                                shadow = ann.shadow();
                                extraStyle = ann.style();
                                annotationFound = true;
                                } else {
                                /* Try field access */
                                try {
                                Field f = beanClass.getDeclaredField(propertyName);
                                if (f.isAnnotationPresent(SmallImage.class)) {
                                SmallImage ann = f.getAnnotation(SmallImage.class);
                                size = ann.size();
                                shadow = ann.shadow();
                                extraStyle = ann.style();
                                annotationFound = true;
                                }
                                } catch (NoSuchFieldException e) {
                                /* ignore */
                                }
                                }
                                } catch (Exception e) {
                                System.out.println("Error reading @SmallImage annotation: " + e.getMessage());
                                e.printStackTrace();
                                }
                                }

                                /* Fallback to request parameters */
                                if (!annotationFound) {
                                String sizeStr = request.getParameter("size");
                                if (sizeStr != null && !sizeStr.isEmpty()) {
                                try {
                                size = Integer.parseInt(sizeStr);
                                } catch (NumberFormatException e) {
                                /* ignore */
                                }
                                }
                                if (request.getParameter("shadow") != null) {
                                shadow = "true".equalsIgnoreCase(request.getParameter("shadow"));
                                }
                                if (request.getParameter("style") != null) {
                                extraStyle = request.getParameter("style");
                                }
                                }

                                String containerClass = "small-image-container";
                                if (shadow) {
                                containerClass += " small-image-shadow";
                                }

                                /* Apply size directly to IMG to avoid inheritance issues */
                                String imgStyle = "width: " + size + "px !important; " +
                                "height: " + size + "px !important; " +
                                "min-width: " + size + "px !important; " +
                                "min-height: " + size + "px !important; " +
                                "max-width: " + size + "px !important; " + /* Prevent expansion */
                                "max-height: " + size + "px !important; " +
                                "object-fit: cover !important; " +
                                "display: block !important; " +
                                "margin: 0 !important; padding: 0 !important;";

                                /* Container just wraps it */
                                String containerStyle = extraStyle;
                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- DEBUG INFO: annotationFound=");
      out.print(annotationFound);
      out.write(", size=");
      out.print(size);
      out.write(", shadow=");
      out.print(shadow);
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("                                ");
 if (value !=null && !foid.isEmpty()) { 
      out.write("\r\n");
      out.write("                                    <div class=\"");
      out.print(containerClass);
      out.write("\" style=\"");
      out.print(containerStyle);
      out.write("\">\r\n");
      out.write("                                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/xava/xfile?application=");
      out.print(applicationName);
      out.write("&module=");
      out.print(module);
      out.write("&fileId=");
      out.print(foid);
      out.write("\"\r\n");
      out.write("                                            style=\"");
      out.print(imgStyle);
      out.write("\" alt=\"Foto\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    ");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
