/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-19 20:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xava.editors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.openxava.model.meta.MetaProperty;

public final class timeSpinnerEditor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("org.openxava.model.meta.MetaProperty");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      org.openxava.web.style.Style style = null;
      style = (org.openxava.web.style.Style) _jspx_page_context.getAttribute("style", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (style == null){
        style = new org.openxava.web.style.Style();
        _jspx_page_context.setAttribute("style", style, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("    ");
 String propertyKey=request.getParameter("propertyKey"); MetaProperty p=(MetaProperty)
        request.getAttribute(propertyKey); String fvalue=(String) request.getAttribute(propertyKey + ".fvalue" ); if
        (fvalue==null || fvalue.isEmpty()) fvalue="00:00" ; boolean editable="true"
        .equals(request.getParameter("editable")); String disabled=editable ? "" : "disabled" ; boolean
        label=org.openxava.util.XavaPreferences.getInstance().isReadOnlyAsLabel(); boolean
        esNegativo=fvalue.startsWith("-"); String valorLimpio=esNegativo ? fvalue.substring(1) : fvalue; String[]
        partes=valorLimpio.split(":"); int horas=0; int minutos=0; try { if (partes.length>= 1) horas =
        Integer.parseInt(partes[0].trim());
        if (partes.length >= 2) minutos = Integer.parseInt(partes[1].trim());
        } catch (NumberFormatException e) {}
        String horasStr = String.format("%02d", horas);
        String minutosStr = String.format("%02d", minutos);
        String signo = esNegativo ? "-" : "+";
        String toggleClass = esNegativo ? "ts-neg" : "ts-pos";
        String propJS = propertyKey.replace(".", "_");
        if (editable || !label) {
        
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            .ts-wrap {\r\n");
      out.write("                display: inline-flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 4px;\r\n");
      out.write("                background: #f8f9fa;\r\n");
      out.write("                border: 1px solid #ced4da;\r\n");
      out.write("                border-radius: 6px;\r\n");
      out.write("                padding: 4px 8px;\r\n");
      out.write("                font-family: monospace\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-btn {\r\n");
      out.write("                border: none;\r\n");
      out.write("                background: #6c757d;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                font-size: 10px;\r\n");
      out.write("                border-radius: 3px;\r\n");
      out.write("                width: 24px;\r\n");
      out.write("                height: 16px\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-btn:hover {\r\n");
      out.write("                background: #495057\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-btn:disabled {\r\n");
      out.write("                opacity: .5;\r\n");
      out.write("                cursor: not-allowed\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-toggle {\r\n");
      out.write("                width: 28px;\r\n");
      out.write("                height: 28px;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                font-weight: bold\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-pos {\r\n");
      out.write("                background: #d4edda;\r\n");
      out.write("                color: #155724\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-neg {\r\n");
      out.write("                background: #f8d7da;\r\n");
      out.write("                color: #721c24\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-val {\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                min-width: 28px;\r\n");
      out.write("                text-align: center\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-grp {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: center\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-sep {\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                color: #6c757d\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ts-lbl {\r\n");
      out.write("                font-size: 9px;\r\n");
      out.write("                color: #6c757d\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("        <div class=\"ts-wrap\" id=\"wrap_");
      out.print(propertyKey);
      out.write("\">\r\n");
      out.write("            <button type=\"button\" class=\"ts-toggle ");
      out.print(toggleClass);
      out.write("\" id=\"tgl_");
      out.print(propertyKey);
      out.write('"');
      out.write(' ');
      out.print(disabled);
      out.write("\r\n");
      out.write("                onclick=\"tglSign_");
      out.print(propJS);
      out.write("()\"><span id=\"sgn_");
      out.print(propertyKey);
      out.write("\">\r\n");
      out.write("                        ");
      out.print(signo);
      out.write("\r\n");
      out.write("                    </span></button>\r\n");
      out.write("            <div class=\"ts-grp\">\r\n");
      out.write("                <button type=\"button\" class=\"ts-btn\" ");
      out.print(disabled);
      out.write(" onclick=\"chgH_");
      out.print(propJS);
      out.write("(1)\">&#9650;</button>\r\n");
      out.write("                <span class=\"ts-val\" id=\"hrs_");
      out.print(propertyKey);
      out.write("\">\r\n");
      out.write("                    ");
      out.print(horasStr);
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("                <button type=\"button\" class=\"ts-btn\" ");
      out.print(disabled);
      out.write(" onclick=\"chgH_");
      out.print(propJS);
      out.write("(-1)\">&#9660;</button>\r\n");
      out.write("                <span class=\"ts-lbl\">HRS</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"ts-sep\">:</span>\r\n");
      out.write("            <div class=\"ts-grp\">\r\n");
      out.write("                <button type=\"button\" class=\"ts-btn\" ");
      out.print(disabled);
      out.write(" onclick=\"chgM_");
      out.print(propJS);
      out.write("(1)\">&#9650;</button>\r\n");
      out.write("                <span class=\"ts-val\" id=\"min_");
      out.print(propertyKey);
      out.write("\">\r\n");
      out.write("                    ");
      out.print(minutosStr);
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("                <button type=\"button\" class=\"ts-btn\" ");
      out.print(disabled);
      out.write(" onclick=\"chgM_");
      out.print(propJS);
      out.write("(-1)\">&#9660;</button>\r\n");
      out.write("                <span class=\"ts-lbl\">MIN</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"hidden\" name=\"");
      out.print(propertyKey);
      out.write("\" id=\"");
      out.print(propertyKey);
      out.write("\" value=\"");
      out.print(fvalue);
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            (function () {\r\n");
      out.write("                var pk = '");
      out.print(propertyKey);
      out.write("', pjs = '");
      out.print(propJS);
      out.write("';\r\n");
      out.write("                window['tglSign_' + pjs] = function () { var s = document.getElementById('sgn_' + pk), t = document.getElementById('tgl_' + pk), n = s.textContent === '-'; s.textContent = n ? '+' : '-'; t.className = 'ts-toggle ' + (n ? 'ts-pos' : 'ts-neg'); upd() };\r\n");
      out.write("                window['chgH_' + pjs] = function (d) { var e = document.getElementById('hrs_' + pk), v = parseInt(e.textContent) + d; if (v < 0) v = 0; if (v > 99) v = 99; e.textContent = v.toString().padStart(2, '0'); upd() };\r\n");
      out.write("                window['chgM_' + pjs] = function (d) { var e = document.getElementById('min_' + pk), h = document.getElementById('hrs_' + pk), v = parseInt(e.textContent) + d; if (v >= 60) { v = 0; var hv = parseInt(h.textContent) + 1; if (hv <= 99) h.textContent = hv.toString().padStart(2, '0') } else if (v < 0) { var hv = parseInt(h.textContent); if (hv > 0) { v = 59; h.textContent = (hv - 1).toString().padStart(2, '0') } else { v = 0 } } e.textContent = v.toString().padStart(2, '0'); upd() };\r\n");
      out.write("                function upd() { var s = document.getElementById('sgn_' + pk).textContent, h = document.getElementById('hrs_' + pk).textContent, m = document.getElementById('min_' + pk).textContent, val = h + ':' + m; if (h === '00' && m === '00') val = '00:00'; else if (s === '-') val = '-' + val; document.getElementById(pk).value = val }\r\n");
      out.write("            })();\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            ");
      out.print(fvalue);
      out.write("&nbsp;\r\n");
      out.write("                ");
 } if (!editable) { 
      out.write("\r\n");
      out.write("                    <input type=\"hidden\" name=\"");
      out.print(propertyKey);
      out.write("\" value=\"");
      out.print(fvalue);
      out.write("\">\r\n");
      out.write("                    ");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
